remove constraint that Status List Token must not use a MAC
oauth-wg/draft-ietf-oauth-status-list pull request #185
Opened 2024-10-20 14:52 UTC by paulbastian

Closes #111

2024-10-20 15:30 UTC, c2bo requested changes
Document history entry is missing and I think we should also adjust line 90

> A Status List may either be provided via HTTPS or be signed and embedded into a Status List Token, whereas this document defines its representations in JWT and CWT.

2024-10-20 15:54 UTC, c2bo approved these changes

2024-10-21 08:54 UTC, tplooker commented on draft-ietf-oauth-status-list.md
> +2. The CWT MUST be secured using a cryptographic signature or MAC algorithm. Relying Parties MUST reject JWTs with an invalid signature.
```suggestion
2. The CWT MUST be secured using a cryptographic signature or MAC algorithm. Relying Parties MUST reject CWTs with an invalid signature.
```

2024-10-21 08:54 UTC, tplooker reviewed
One typo otherwise looks good.

2024-10-21 18:10 UTC, tplooker approved these changes

2024-10-21 18:10 UTC, merged